spring.config.import=classpath:/application-common.properties
server.port=8089
server.servlet.context-path=/api/push-gateway
spring.application.name=push-gateway
spring.application.version=1.0.0

# Kafka
spring.kafka.consumer.group-id=push-gateway-group